// Generated by CoffeeScript 1.6.2
(function() {
  var Game, init;

  $(function() {
    return init();
  });

  init = function() {
    window.canvas = $('#gameCanvas');
    window.canvas[0].width = $("#main").width();
    window.canvas[0].height = $("#main").height();
    window.game = new Game();
    window.context = window.canvas[0].getContext('2d');
    return this.canvas.click('mouseclick', function(e) {
      window.game.addPoint(e.offsetX - 25, e.offsetY - 25);
      return window.game.doDraw(window.context);
    }, false);
  };

  Game = (function() {
    function Game() {
      this.points = [];
    }

    Game.prototype.addPoint = function(x, y) {
      return this.points.push([x, y]);
    };

    Game.prototype.doDraw = function(ctx) {
      var point, _i, _len, _ref, _results;

      console.log("@points: ", this.points);
      ctx.fillStyle = "#FF0000";
      _ref = this.points;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        _results.push(ctx.fillRect(point[0], point[1], 50, 50));
      }
      return _results;
    };

    return Game;

  })();

}).call(this);
